// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxynIQedGUttwWufwNwsQvWXKldhsoUxQ',
    appId: '1:556121620278:android:bb0158f49e089ae6aefd97',
    messagingSenderId: '556121620278',
    projectId: 'elite-group-chat',
    databaseURL: 'https://elite-group-chat-default-rtdb.firebaseio.com',
    storageBucket: 'elite-group-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDun8oXVqGbXcihtWhXyqezwuyORCDV9RU',
    appId: '1:556121620278:ios:22bfb3641e693982aefd97',
    messagingSenderId: '556121620278',
    projectId: 'elite-group-chat',
    databaseURL: 'https://elite-group-chat-default-rtdb.firebaseio.com',
    storageBucket: 'elite-group-chat.appspot.com',
    iosClientId: '556121620278-4b5p7g72ad5uk7ejr0f5sla6vjaao1i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.twilite',
  );
}
